# 1. Create a 3x3x3 array with random values

In [4]:
import numpy as np
random_array = np.random.rand(3, 3, 3)
print(random_array)

[[[0.53014877 0.21511448 0.11451959]
  [0.6485     0.70419599 0.20997636]
  [0.85573344 0.91367459 0.313345  ]]

 [[0.24234714 0.94968758 0.83440982]
  [0.43926406 0.16221917 0.44060612]
  [0.3710831  0.88806776 0.97486356]]

 [[0.81923131 0.74306787 0.95696461]
  [0.07460499 0.34465213 0.68940507]
  [0.02687334 0.22694281 0.06223956]]]


# 2. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [5]:
import numpy as np
matrix = np.diag(1 + np.arange(4), k=-1)
print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3. Create a 8x8 matrix and fill it with a checkerboard pattern

In [7]:
import numpy as np
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [11]:
import numpy as np
nums = np.random.rand(5, 5)
print("Original array elements:")
print(nums)
col_means = np.mean(nums, axis=0)
arr_normalized = (nums - col_means) / np.std(nums, axis=0)
print("Original Array:")
print(nums)
print("\nNormalized Array (column-wise):")
print(arr_normalized)

Original array elements:
[[0.13052487 0.80839778 0.96168827 0.81498578 0.60818431]
 [0.42381065 0.75784952 0.46398724 0.62848639 0.58657236]
 [0.03408952 0.45115612 0.48415867 0.92913724 0.93447703]
 [0.92189249 0.40874821 0.67267673 0.32959609 0.58527052]
 [0.97966157 0.74673165 0.15302355 0.29720441 0.66800462]]
Original Array:
[[0.13052487 0.80839778 0.96168827 0.81498578 0.60818431]
 [0.42381065 0.75784952 0.46398724 0.62848639 0.58657236]
 [0.03408952 0.45115612 0.48415867 0.92913724 0.93447703]
 [0.92189249 0.40874821 0.67267673 0.32959609 0.58527052]
 [0.97966157 0.74673165 0.15302355 0.29720441 0.66800462]]

Normalized Array (column-wise):
[[-0.93796462  1.02915705  1.55849174  0.85005323 -0.51583886]
 [-0.18935665  0.72987179 -0.31246287  0.11303969 -0.67902235]
 [-1.18411454 -1.08599307 -0.23663457  1.30116015  1.94787201]
 [ 1.08199051 -1.33708108  0.47204133 -1.06812335 -0.6888521 ]
 [ 1.22944529  0.66404531 -1.48143563 -1.19612971 -0.0641587 ]]


# 5. How to find common values between two arrays?

In [13]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


# 6. How to get the dates of yesterday, today and tomorrow?

In [14]:
from datetime import datetime, timedelta

today = datetime.now()
yesterday = today - timedelta(days=1)
tomorrow = today + timedelta(days=1)

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)

Yesterday: 2023-09-20 14:41:15.436827
Today: 2023-09-21 14:41:15.436827
Tomorrow: 2023-09-22 14:41:15.436827


# 7. Consider two random array A and B, check if they are equal

In [16]:
import numpy as np
x = np.random.randint(0,2,6)
print("First array:")
print(x)
y = np.random.randint(0,2,6)
print("Second array:")
print(y)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)

First array:
[1 1 0 0 1 1]
Second array:
[1 1 0 1 1 0]
Test above two arrays are equal or not!
False


# 8.Create random vector of size 10 and replace the maximum value by 0

In [21]:
import numpy as np
x = np.random.random(10)
print("Original array:")
print(x)
x[x.argmax()] = 0
print("Maximum value replaced by 0:")
print(x)

Original array:
[0.13393253 0.72641345 0.61442588 0.49610666 0.92526477 0.44227204
 0.46403618 0.38156195 0.84424075 0.32744169]
Maximum value replaced by 0:
[0.13393253 0.72641345 0.61442588 0.49610666 0.         0.44227204
 0.46403618 0.38156195 0.84424075 0.32744169]


# 9. How to print all the values of an array?

In [17]:
import numpy as np
my_array = np.array([1, 2, 3, 4, 5])
print(my_array)

[1 2 3 4 5]


# 10.Subtract the mean of each row of a matrix

In [23]:
import numpy as np
print("Original matrix:\n")
X = np.random.rand(5, 10)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.31718496 0.16101443 0.25623781 0.16736917 0.43024048 0.11055169
  0.20248448 0.70383157 0.48479317 0.38557616]
 [0.58714181 0.38879825 0.40514671 0.22792204 0.46381933 0.81448364
  0.25237103 0.67242053 0.01724588 0.62596965]
 [0.9790412  0.94792365 0.11795944 0.23773696 0.47012645 0.78924255
  0.52950981 0.83644409 0.63308074 0.06012892]
 [0.09966432 0.56187691 0.49369496 0.43716502 0.70502928 0.62127902
  0.9292402  0.63959574 0.27227473 0.81559869]
 [0.59282217 0.21991991 0.34770444 0.22109883 0.90195685 0.55032491
  0.83886648 0.82108507 0.14753711 0.08050424]]

Subtract the mean of each row of the said matrix:

[[-0.00474343 -0.16091396 -0.06569058 -0.15455922  0.10831208 -0.2113767
  -0.11944391  0.38190318  0.16286478  0.06364777]
 [ 0.14160992 -0.05673363 -0.04038518 -0.21760985  0.01828745  0.36895175
  -0.19316086  0.22688864 -0.428286    0.18043776]
 [ 0.41892182  0.38780427 -0.44215994 -0.32238242 -0.08999293  0.22912317
  -0.03060957  0.27632471  0.07

# 11. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [26]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[3. 3. 2. 4. 5. 3. 2. 4. 3. 1.]


# 12.How to get the diagonal of a dot product?

In [28]:
import numpy as np
a = np.random.rand(1000,200)
b = np.random.rand(200,200)
print(np.diag(np.dot(a, b)))
print(a)

[52.47487898 52.20352114 48.44998743 53.31340345 39.87494273 47.79028303
 52.82223057 57.19572797 52.81369313 47.75969723 47.91253157 51.14179878
 55.81486391 49.04174699 51.13924367 46.68859081 49.66478996 52.5826935
 46.50637189 49.89498806 48.46468641 49.61319102 44.49406439 54.30846152
 48.35174521 50.78487792 49.8967627  51.07734075 43.87369779 50.29704037
 55.86417771 52.21264484 50.71132425 49.7376617  48.36799829 48.93301815
 51.92772529 49.65144334 49.47292192 50.257864   52.59832874 50.02225986
 48.17351592 42.56880636 51.51021092 49.47071121 51.94711193 52.54851904
 47.84819651 54.15716015 48.66890733 47.69033247 47.22461384 43.85110289
 48.91258882 49.99807117 48.71417647 45.85965031 51.74560918 52.35049338
 48.21731286 50.09309525 48.90057097 48.94305042 51.02136007 55.97433844
 49.27953805 50.82984796 53.91073489 53.31778182 50.16788317 46.99986967
 45.84200769 44.82619394 50.64834708 53.13114101 54.89394699 47.79977456
 50.24503258 50.63320478 53.8484205  53.2078931  48.

# 13. How to find the most frequent value in an array?

In [31]:
import numpy as np
x = np.random.randint(0, 10, 40)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[8 2 4 4 6 1 7 3 8 2 8 2 6 3 0 4 7 0 0 5 8 3 9 3 5 8 3 7 3 0 1 9 1 4 9 3 2
 0 7 8]
Most frequent value in the above array:
3


# 14. How to get the n largest values of an array

In [33]:
import numpy as np
x = np.arange(10)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])

Original array:
[0 1 2 3 4 5 6 7 8 9]
[9]


# 15. How to create a record array from a regular array?

In [35]:
import numpy as np
names = ['Alice', 'Bob', 'Charlie']
scores = [85, 92, 78]
record_array = np.rec.fromarrays([names, scores], names=['Name', 'Score'])
print(record_array)

[('Alice', 85) ('Bob', 92) ('Charlie', 78)]


# 16. How to swap two rows of an array

In [36]:
import numpy as np
a = np.array([[4,3, 1],[5 ,7, 0],[9, 9, 3],[8, 2, 4]]) 
print(a)
a[[0, 2]] = a[[2, 0]]
print(a)

[[4 3 1]
 [5 7 0]
 [9 9 3]
 [8 2 4]]
[[9 9 3]
 [5 7 0]
 [4 3 1]
 [8 2 4]]


# 17. Write a python code to reshape to the next dimension of numpy array

In [37]:
import numpy as np
myarray = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarray = myarray.reshape(4, 2)
print(newarray)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
